FROM clojure:temurin-17-tools-deps-jammy
# Details as of 2023-06-17
# Ubuntu: Ubuntu 22.04 LTS (Jammy Jellyfish)
# JDK: eclipse-temurin 17
# Clojure: tools-deps, 1.11.1.1347

## TODO: add a vscode user?

RUN apt-get update && apt-get install -y gpg curl leiningen
## FIXME: apt-get install leiningen AND java 11, can we block that?
## TODO: still need helm? kustomize? skaffold?

# Install kubectl
RUN curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list && apt-get update && apt-get install -y kubectl

# Install deps-new and clj-new (prefer deps-new, but clj-new is needed for some templates)

RUN clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.5.2"}' :as deps-new
RUN clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "v1.2.399"}' :as clj-new

# Add Babashka

RUN curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install \
    && chmod +x install \
    && ./install --static