version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: ./Dockerfile.dev
    volumes:
      - ../..:/workspaces:cached
    # network_mode: service:mongodb
    command: sleep infinity

# Show another example pg, mongo, s3?
